def error_func():
    pass